version: '3'

volumes:
  bitcoin:

services:
  bitcoind:
    image: kylemanna/bitcoind:latest
    ports:
      - "18333:18333"
    volumes:
      - ./bitcoin:/bitcoin/.bitcoin

  ord:
    build:
      context: ./ordinals
    volumes:
      - ./bitcoin:/bitcoin/.bitcoin
      - ./ordinals/index-data:/ordinals/index-data
    depends_on:
      - bitcoind
    tty: true